# Generated by Django 5.2.11 on 2026-02-11 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('surveys_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surveys',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='surveys_app.survey'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
