# Generated by Django 6.0.1 on 2026-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("ENUMERATOR", "Enumerator"),
                    ("F_SUPPERVISOR", "F_SUPPERVISOR"),
                ],
                default="ENUMERATOR",
                max_length=20,
            ),
        ),
    ]
