# Generated by Django 6.0 on 2026-01-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_user_date_joined_alter_profile_user_and_more'),
        ('surveys_app', '0002_remove_survey_user_survey_users_delete_surveytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surveys',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='surveys_app.survey'),
        ),
    ]
