# Generated by Django 6.0.1 on 2026-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0002_alter_user_email_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_temporary_password",
            field=models.BooleanField(default=True),
        ),
    ]
