# Generated by Django 6.0 on 2026-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_user_surveys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='survey_types',
            field=models.JSONField(blank=True, default=list, help_text='Choose survey types assigned to the user'),
        ),
    ]
