# Generated by Django 6.0.1 on 2026-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0004_alter_user_is_temporary_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_temporary_password",
            field=models.BooleanField(default=True),
        ),
    ]
