# Generated by Django 6.0 on 2026-02-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_user_survey_types'),
        ('account_app', '0005_alter_user_is_temporary_password'),
    ]

    operations = [
    ]
