# Generated by Django 6.0 on 2026-02-05 09:50

import account_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_merge_20260203_1535'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account_app.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ENUMERATOR', 'Enumerator'), ('F_SUPERVISOR', 'Field Supervisor'), ('TEAM_LEADER', 'Team Leader'), ('SURVEY_MANAGER', 'Survey Manager')], default='ENUMERATOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='survey_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set_permissions', to='auth.permission'),
        ),
    ]
