# Generated by Django 5.2.11 on 2026-02-11 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('survey_type', models.CharField(choices=[('HEALTH', 'Health'), ('AGRICULTURE', 'Agriculture'), ('EDUCATION', 'Education'), ('ENVIRONMENT', 'Environment'), ('LFS', 'LFS'), ('SAS', 'SAS'), ('EICV', 'EICV'), ('HOUSEHOLD', 'Household')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
