# Generated by Django 6.0 on 2026-01-26 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
        migrations.AddField(
            model_name='survey',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SurveyTask',
        ),
    ]
