# Generated by Django 6.0 on 2026-01-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0002_remove_survey_user_survey_users_delete_surveytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('AGRICULTURE', 'Agriculture'), ('EDUCATION', 'Education'), ('ENVIRONMENT', 'Environment'), ('HEALTH', 'LFS'), ('AGRICULTURE', 'SAS'), ('EDUCATION', 'EICV'), ('ENVIRONMENT', 'household')], max_length=50),
        ),
    ]
