# Generated by Django 6.0 on 2026-02-03 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0003_alter_survey_survey_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='users',
        ),
        migrations.AddField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('HEALTH', 'Health'), ('AGRICULTURE', 'Agriculture'), ('EDUCATION', 'Education'), ('ENVIRONMENT', 'Environment'), ('LFS', 'LFS'), ('SAS', 'SAS'), ('EICV', 'EICV'), ('HOUSEHOLD', 'Household')], max_length=50),
        ),
    ]
