# Generated by Django 5.2.11 on 2026-02-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_app', '0004_remove_survey_created_at_remove_survey_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
